#!/usr/bin/env php
<?php

require __DIR__ . '/global-inc.php';

//\YusamHub\AppExt\SymfonyExt\ConsoleKernel::$isDebugging = true;

$consoleKernel = new \YusamHub\AppExt\SymfonyExt\ConsoleKernel(app_ext()->getRootDir());
$consoleKernel->run();

